language: java
jdk:
- oraclejdk8
sudo: required
services:
- postgres
env:
  global:
  - secure: ZH8wNu6D7B/7MS3thtJ6D+RdJRVqPdq9Kg85W1vG+KPwSFKrD2MRDCdiodoewjUsmd4lc9WxvJwtCzQEkk4pzH/b2HkXXWHLYLYFtnsS3m0qX82V5+HuSrZqkXmYmEYM9K3izQOEhTifFyIqMltHIqj/4F65RcCJ3QfJ+pK7v5w2l5BfVQeHJVf7sw78wzSXOaThK2GVKYaLqvbr13zW6BxYjjo+9Db3ZvD0KhGq482q4gzHAUNqZD08rM/4SjGMK3HnSl1AFj60arthnTtSexErnP+Y+XcqQRQZR0Xxt3cqr0hy5B0L/f2FxJEnTbIq+uWrJuE58jifIP8gwWiNTHteHks1dULR18FzybRQRxWzpwuak8R5XqPOHS9KoeXU8bw4sWxbjVcvdFNeBOR9QWF7e6Vx/1hSXVLY3LH4ofW7NoF78kroh0QnMM9r6vZWZs2CwtrEC6LHJT0bBPmyxym5Nqqy7GZ5keaCdeh/9XOxKkXoPNOmNJ07EQZsLCSSY+QJp70B6h0fq9XEK5UcvzXliNB7rhLPF9+aK7lhhJZ88aYR9DBmHx5eKx2o82jmEFaYueZi7fNlRK0m+4OWqupx5uHaFCD4AjznUl/3mJBpD/JjsdW+WuJQgApfqOYHMrbjf+0uhiA+yT/bq8BNvGLpmb4iFgD67e2QTERdScQ=
  - secure: ScasJTKiZ14shWtOp3ck86QGn3ISmqBb1YtMV1a+6ZTB81cd3WW2xhW3V8LuZoRX3wfqGWUI9U8v/EfPFe1BHaDVssPo4hC/qn6u5+law3P7ui2aPgcF3oSKrKpkdNkTMJ+x5p6EFvxx2SIGleevXiHXVFw80vPARafMvurKBoCyOikMEbHPmDQ9RbSHuAhCuxrWZvaJj9TpXL/cDDP1sRSvHZf70jr2C8fRFkZ7GlC1kL9g9Hz5CSXT/3Zd415O4ODbmLYUdbZSgcTrCZcG+RheZJPbgpYYDDSJPnTxMAjQGZr25IEwBdfIi23hxjv0xjgBTjH67cb6GsA+mfnj68jrj2Wvr9Amn0EF1zT7ByXt7Q/ml+jCnmX2NqHTEvaZMDT7Lqj203hRLoJgSI8hHw8F3V3XhOUxljUoqoDmpnrPjC05neyyuhNAcoCOBZut4K+xDdCgRTG4G006vhXC0V8HfqPNFbDHjB99qmn+Dyw70qhoCDSOUXlgj8jtp1NKm8dKvyl9eSLZqWf0kxKNJGd971paqFsWFOaKah50a5iQVY49ecXdibr0CMQoEtHt6Oqd/Ca6lWKM8uGLpq//RqOF8b8rUQg8yO5S1tt8yfTJ+JwIm//tvbwslG/tKhqA7aDRkKzqgwQyQ8yRtvK1I//IXWukA6aF3rpdZ+lTzo0=
before_install:
- echo "Testing Docker Hub credentials"
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- echo "Docker Hub credentials are working"
after_success:
- export ACTUAL_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "Test Success - Branch($TRAVIS_BRANCH) Actual($ACTUAL_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)
  Tag($TRAVIS_TAG) Commit($TRAVIS_COMMIT) PR($TRAVIS_PULL_REQUEST) Build($TRAVIS_BUILD_NUMBER)"
- if [[ "$ACTUAL_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub";
  fi
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- export REPO=aista/passenger
- export TAG=`if [ "$ACTUAL_BRANCH" == "master" ]; then echo "latest";else echo "";
  fi`
- docker build -f Dockerfile -t $REPO:$TAG .
- docker push $REPO