version: "3"

services:
  passenger:
    build: ./
    volumes:
      - ./src:/usr/src/app
    ports:
      - '8080:8080'
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'passenger_db'
      POSTGRES_PASSWORD: "aitestingsecretpassword"
      POSTGRES_USER: "admin"
      PGDATA: ./postgres-data
    ports:
      - '5432:5432'
    volumes:
      - ./db_volume:/var/lib/postgresql
