version: "3"

services:
  passenger:
    build: ./
    volumes:
      - ./src:/usr/src/app
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'passenger_db'
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      PGDATA: ./postgres-data
    ports:
      - '5432:5432'
    volumes:
      - ./db_volume:/var/lib/postgresql

  discoveryservice:
    image: aista/eureka
    ports:
      - '8761:8761'
    environment:
      - 'eviction-internal-timer-in-ms: 1000'
