version: "3"

services:
  passenger:
    build: ./
    volumes:
        - ./src:/usr/src/myapp
    links:
        - postgres        
  postgres:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'aitestingsecretpassword'
      POSTGRES_DB: 'passenger'
    volumes:
      - pgdata:/docker-entrypoint-initdb.d/
volumes:
  pgdata:

