
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/passenger_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jpa.hibernate.ddl-auto: create-drop

liquibase.changeLog: classpath:/db/changelog/Changelog.xml

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery-service:8761/eureka/

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

---
#spring:
#  profiles: test
#  datasource:
#    url: jdbc:postgresql://localhost:5432/passenger_db
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
#  jpa.hibernate.ddl-auto: create-drop
#
#liquibase.changeLog: classpath:/db/changelog/Changelog.xml
#
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#        defaultZone: http://localhost:8761/eureka/