
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/passenger_db
    username: admin
    password: aitestingsecretpassword
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jpa.hibernate.ddl-auto: create-drop
#spring.jpa.properties.hibernate.default_schema = passenger_dbp

#Disable Eureka
#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false

#logging.level.root=DEBUG
liquibase.changeLog: classpath:/db/changelog/Changelog.xml

#spring.jpa.hibernate.ddl-auto=none
#spring.h2.console.enabled=true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discovery-service:8761/eureka/

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/passenger_db
    username: admin
    password: aitestingsecretpassword
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jpa.hibernate.ddl-auto: create-drop
#spring.jpa.properties.hibernate.default_schema = passenger_dbp

#Disable Eureka
#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false

#logging.level.root=DEBUG
liquibase.changeLog: classpath:/db/changelog/Changelog.xml

#spring.jpa.hibernate.ddl-auto=none
#spring.h2.console.enabled=true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/